### ISSUE TITLE
Support of bearer security schema

### ISSUE THREAD

**Issue by psamusev** [karlvr/openapi-generator-plus#13]
https://github.com/karlvr/openapi-generator-plus/blob/efbaf8ff567a9a64683f23be65d31572f4ae2a70/packages/core/src/process/security.ts#L145 doesn't contain any code which related to 'Bearer' authentication type.

Proposal: Add `isBearer` flag to simplify identification in generators implementations

**Comment by karlvr** [comment]
@psamusev thanks for your comments. Bearer is a common auth scheme, but any scheme could be specified in the `scheme` attribute (the values _should_ come from https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml). So I don't think it's appropriate to add `isBearer` here... it's sort of to make up for the templating language sucking, which I hope to change :-) So I'm going to close this and pick it up in the generator.
