### ISSUE TITLE
Add NestJS server stub generator

### ISSUE THREAD

**Issue by psamusev** [karlvr/openapi-generator-plus#30]
NestJS is a popular node js framework to authoring the backend. Would be nice to have corresponding generator to generate NestJS based server from open api spec

**Comment by karlvr** [comment]
@psamusev thank you for the suggestion. I would welcome a generator template for this and any other environment. Are you interested in creating it?

Things are _reasonably_ settled in the project now and I think we're approaching a 1.0.0 for the core.

I'd be happy to improve the documentation for building a generator template to help!

**Comment by psamusev** [comment]
@karlvr Do we already have documentation about custom generator creation that I or anyone else can follow to create this one?

**Comment by karlvr** [comment]
@psamusev Not reaaaallllyyy… I've just been on a process of improving the documentation for users. Nearly all of the generator templates are in the other repository. I have started two new generator templates in separate repositories recently. 

I am guessing the NestJS server stub would be most similar to the https://github.com/karlvr/openapi-generator-plus-express-passport one. Is that right?

I would start a new project by copying that one and then tweaking the templates as desired. There's very little typescript. Lots of handlebars. 

There are built in tests so you can run the tests and see what it outputs. 

If you choose to I will document whatever bits of the process you need!

**Comment by psamusev** [comment]
> I am guessing the NestJS server stub would be most similar to the https://github.com/karlvr/openapi-generator-plus-express-passport one. Is that right?

Somehow yes, it can be considered as a wrapper to `express` with Module system. 

I may try to create the generator during my free time if you like with base of `express-passport` if it's done and works.

Should it be also separate repo?

**Comment by karlvr** [comment]
@psamusev that's fantastic. You can make your own repo, and with the right keywords in the `package.json` it will show up as an option in the create script etc. Thats very exciting.
