### ISSUE TITLE
how to enlarge the entry limit

### ISSUE THREAD

**Issue by tencyle-assaft** [karlvr/openapi-generator-plus#45]
hi, 

i need to get large entry on the body. i get the following error:
PayloadTooLargeError: request entity too large
    at readStream (/Users/assaftamir/wo/backend_service/node_modules/raw-body/index.js:163:17)
    at getRawBody (/Users/assaftamir/wo/backend_service/node_modules/raw-body/index.js:116:12)
 

how can i enlarge if?

Thanks,
Assaf

**Comment by stevegoossens** [comment]
This sounds more like a general Express question, which should be solvable by making use of the Express configuration, e.g.
```
app.use(express.json({limit: '50mb'}));
app.use(express.urlencoded({limit: '50mb'}));
```
source: https://stackoverflow.com/a/19965089/1456285

**Comment by tencyle-assaft** [comment]
thanks!
