### ISSUE TITLE
Release 2.7.0 broken `Cannot find module 'pluralize'`

### ISSUE THREAD

**Issue by ktalebian** [karlvr/openapi-generator-plus#48]
The new release is broken:

```
Error: Cannot find module 'pluralize'
```

This is coming from https://github.com/karlvr/openapi-generator-plus/blob/main/packages/core/src/process/schema/index.ts#L25 

This package is not included:

```bash
❯ npm ls pluralize
@cg/gateway@1.0.0 .../application/gateway
└── (empty)
```

**Comment by karlvr** [comment]
@ktalebian thank you, sorry about that! A fixed release is coming out now.

**Comment by karlvr** [comment]
2.8.1 is now available with this fixed.
